Internal Server Error: /api/history/USD/to/CAD/
"GET /api/history/USD/to/CAD/ HTTP/1.1" 500 5363
Internal Server Error: /api/history/USD/to/CAD/
"GET /api/history/USD/to/CAD/ HTTP/1.1" 500 5363
Internal Server Error: /api/history/USD/to/CAD/
"GET /api/history/USD/to/CAD/ HTTP/1.1" 500 5363
Internal Server Error: /api/history/USD/to/CAD/
"GET /api/history/USD/to/CAD/ HTTP/1.1" 500 5366
Internal Server Error: /api/history/USD/to/CAD/
"GET /api/history/USD/to/CAD/ HTTP/1.1" 500 5363
Internal Server Error: /api/history/USD/to/CAD/
"GET /api/history/USD/to/CAD/ HTTP/1.1" 500 5363
Internal Server Error: /api/history/USD/to/CAD/
"GET /api/history/USD/to/CAD/ HTTP/1.1" 500 5363
Internal Server Error: /api/current/${fromCurrency}/to/${toCurrency}/
Traceback (most recent call last):
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/crash/Programs/Henon/backend/henon/lib/python3.9/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/Users/crash/Programs/Henon/backend/convert/api/views.py", line 14, in convert_currency_latest
    conversion_result = convert_current_currency_service(base_currency,target_currency)
  File "/Users/crash/Programs/Henon/backend/convert/api/services.py", line 45, in convert_current_currency_service
    raise ValueError(f"Base currency '{base_currency}' does not exist in the database")
ValueError: Base currency '${fromCurrency}' does not exist in the database
"GET /api/current/$%7BfromCurrency%7D/to/$%7BtoCurrency%7D/ HTTP/1.1" 500 98827
